name: publish-powershell-gallery
on:
  push:
    branches: [ main]
    tags: [ 'v*.*.*' ]
jobs:
  publish-powershell-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PGALLERY }}




